
name: MYSQL
on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: myapp
      MYSQL_DB: sample_rails_mysql_test
      MYSQL_PASSWORD: ${{ secrets.RAILS_TEST_DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.RAILS_TEST_DB_ROOT_PASSWORD }}
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Debug
        run: |
          mysql --host=127.0.0.1 --user=${{ env.MYSQL_USER }} --password={{ env.MYSQL_PASSWORD }} ${{ env.MYSQL_DB }} <<MY_QUERY
          SHOW GRANTS;
          MY_QUERY
