name: Cache self
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Repository
      uses: actions/cache@v3
      with:
        path: |
          ~/
          !~/.git/
