name: Cache self
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Cache Repository
      uses: actions/cache@v3
      with:
        path: |
          ~/
          !~/.git/
